[workspace]
members = ["codec", "macros", "stream", "stream/macros", "transport/tcp", "transport/rdma", "transport/quic", "test-suite", ]

[package]
name = "razor-rpc"
version = "0.8.0"
edition = "2024"
authors = ["plan <frostyplanet@gmail.com>"]
categories = ["concurrency", "network-programming"]
repository = "https://github.com/NaturalIO/razor-rpc"
documentation = "https://docs.rs/razor-rpc"
keywords = ["networking", "rpc"]
readme = "README.md"
license = "MIT"
description = """
razor-rpc is a modular, pluggable RPC for high throughput scenario, supports various runtimes,
with a low-level streaming interface, and high-level remote API call interface.
"""

[dependencies]
log = { version = "0.4", features = ["std", "kv_unstable"] }
captains-log = ">=0.15"
io-buffer = "1"
serde = "1"
async-trait = "0"
crossfire = ">=3.1"
orb = "0"
razor-stream = {path="stream/", version=">=0.8"}
razor-rpc-macros = { path = "macros", version = ">=0.8" }
ahash = "0.8"

[dev-dependencies]
serde_derive = "1"
nix = "0"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
razor-rpc-tcp = {path="transport/tcp/", version = "0"}
razor-rpc-codec = {path="codec/", version="0", features=["msgpack"]}
orb-tokio = { version="0" }

[package.metadata.docs.rs]
all-features = true
# enable features in the documentation
rustdoc-args = ["--cfg", "docsrs"]

[features]

[workspace.lints.clippy]
new_ret_no_self = "allow"
needless_range_loop = "allow"
type_complexity = "allow"
needless_return = "allow"
mut_from_ref = "allow"
transmute_ptr_to_ref = "allow"
len_without_is_empty = "allow"
result_unit_err = "allow"
module_inception = "allow"

[lints]
workspace = true
