[package]
name = "razor-stream"
version = "0.4.0"
edition = "2024"
authors = ["plan <frostyplanet@gmail.com>"]
categories = ["concurrency", "network-programming"]
repository = "https://github.com/NaturalIO/razor-rpc"
documentation = "https://docs.rs/razor-rpc"
keywords = ["networking", "rpc"]
license = "MIT"
readme = "../README.md"
description = """
The streaming interface of razor-rpc.
razor-rpc is a modular, pluggable RPC for high throughput scenario, supports various runtimes,
with a low-level streaming interface, and high-level remote API call interface.
"""

[dependencies]
libc = "0"
signal-hook = "0"
close_fds = ">=0.3.2"
strum = {version = "0", features = ["derive"]}
nix = "0"
thiserror = "2"
orb = { version="0" }
arc-swap = "1"
razor-rpc-codec = {path="../codec/", version=">=0.3"}
razor-stream-macros = {path="macros", version=">=0.4"}
log = { version = "0.4", features = ["std", "kv_unstable"] }
captains-log = ">=0.15"
futures = "0.3"
zerocopy = { version="0.8", features=["derive"]}
io-buffer = "1"
rustc-hash = "1.1"
serde = "1"
crossfire = ">=3.1"

[dev-dependencies]
num_enum = "0"
serde_derive = "1"
razor-rpc-codec = { path="../codec", version="0", features=["msgpack"] }

[package.metadata.docs.rs]
all-features = true
# enable features in the documentation
rustdoc-args = ["--cfg", "docsrs"]

