name: tokio-x86
permissions:
  contents: read
  pull-requests: write
on:
  schedule: [cron: "10 */5 * * *"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: test all
      run: make test-all -- "-F tokio"

    - name: test presure release
      run: make pressure -- "-F tokio"
